# Generated by Django 5.2.8 on 2025-11-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['-id']},
        ),
    ]
