# Generated by Django 5.2.8 on 2025-11-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='branchcell',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='defaultinfo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='denomination',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='housingstatus',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='leadershiprole',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='maritalstatus',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='membershiplevel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='occupationtype',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-id']},
        ),
    ]
