# Generated by Django 5.2.8 on 2025-11-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_branch_options_alter_branchcell_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-currency_ref']},
        ),
    ]
